name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: install emacs
        run: sudo apt-get update && sudo apt-get install -y emacs
      - name: install agda
        run: sudo apt-get install -y agda
      - name: put prelude in the right place
        run: ln -s $(pwd) $HOME/.emacs.d
      - name: load prelude
        run: emacs --batch --load init.el
