name: CI
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install emacs and agda
        run: |
          brew update
          brew install emacs
          brew install agda
      - name: put prelude in the right place
        run: ln -s $(pwd) $HOME/.emacs.d
      - name: load prelude
        run: emacs --batch --load init.el
